# Generated by Django 3.2.9 on 2021-11-25 13:56

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20211125_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to=job.models.ApplyUpload)),
                ('cover_latter', models.TextField(max_length=500)),
            ],
        ),
    ]
