# Generated by Django 3.2.9 on 2021-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
