# Generated by Django 3.2.9 on 2021-11-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
    ]
